apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: 991232067093.dkr.ecr.ap-south-1.amazonaws.com/kv_backend@sha256:f8e09d7f5ca77c7f0e6a277b287120baeec9711ad1b41200aaaba28bbe72b181
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_USER
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MAIL_PASS
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
